org: pesaurio
service: api-alumnos

provider:
  name: aws
  runtime: python3.12
  timeout: 30  
  iam:
    role: arn:aws:iam::335544015381:role/LabRole

functions: #todo lo de adentro seran lambdas
  listar: #alias dl lambda
    handler: ListarAlumnos.lambda_handler #nombre de la funcion que incia la logica del lambda
    events:
      - http: #existe un apigateway asociado a este lambda 
          path: /alumnos/listar #sobre este path
          method: post
          cors: true
          integration: lambda
  crear: #alias dl lambda
    handler: CrearAlumno.lambda_handler #nombre de la funcion que incia la logica del lambda
    events:
      - http: #existe un apigateway asociado a este lambda 
          path: /alumnos/crear #sobre este path
          method: post
          cors: true
          integration: lambda



